		$(document).ready(function(){
				$('#sdku').mouseover(function(){
					$('.Droplie').css('display','block')
				});
				$('#sdku').mouseleave(function(){
					$('.Droplie').css('display','none')
				});
				$('.Droplie').mouseover(function(){
					$('.Droplie').css('display','block')
				});
				$('.Droplie').mouseleave(function(){
					$('.Droplie').css('display','none')
				});
			})